Adapt CLI to new D-Bus API
yast/d-installer pull request #229
Opened 2022-07-15 15:31 UTC by joseivanlopez

## Problem

Several changes were done in the D-Bus API, and the CLI code is not adapated to such changes yet.

This is a follow-up of https://github.com/yast/d-installer/pull/209.

## Solution

Adapt CLI to the new D-Bus API.

## Testing

* Added new unit tests
* Tested manually

2022-07-20 15:31 UTC, joseivanlopez commented on service/test/dinstaller/dbus/clients/manager_test.rb
> +    # Using partial double because methods are dynamically added to the proxy object
Class Foo does not implement instance method #bar, or something like that.

2022-07-21 15:15 UTC, mvidner requested changes
```sh
cd d-installer/service
bundle exec rspec
```

 2 tests fail because they cannot get the storage lock (as non root).

2022-07-22 12:22 UTC, joseivanlopez commented on service/lib/dinstaller/dbus/clients/manager.rb
> +          @dbus_object.introspect
As discussed on IRC, this call to `#introspect` is still needed.

2022-07-22 12:27 UTC, mvidner commented on service/lib/dinstaller/dbus/clients/manager.rb
> +          @dbus_object.introspect
> if I omit #introspect, then methods like [DBus::Clients::Software#select_product](https://github.com/yast/d-installer/blob/master/service/lib/dinstaller/dbus/clients/software.rb#L70) are not found

2022-07-22 12:49 UTC, mvidner commented
The change from `DBus::Service#object` to `DBus::Service#[]` has silently fixed a bug in `DInstaller::DBus::Clients::Software#provision_selected?` - previously it would return `[true]` or `[false]` which are both truthy.
Checked with irb.

2022-07-22 12:50 UTC, mvidner approved these changes

2022-07-22 12:54 UTC, merged