Modify the packages and patterns to support arch conditional
yast/d-installer pull request #486
Opened 2023-03-21 13:51 UTC by teclator

## Problem

The current configuration does not have arch conditional for the patterns or packages needed by each product, as well as we do not have a general support for it.

## Solution

Extend the current software installation repositories approach supporting the arch conditional also in the software selection

## Testing

- *Added a new unit test*
- *Tested manually*

2023-03-21 14:11 UTC, imobachgs commented on service/lib/dinstaller/software/manager.rb
> +        return true if archs.nil?
`nil?` or `empty?`?

2023-03-21 14:16 UTC, imobachgs commented on service/lib/dinstaller/software/manager.rb
> +        return true if archs.nil?
Just forget about it. It is fine as it is.

2023-03-22 07:37 UTC, imobachgs approved these changes

2023-03-22 08:45 UTC, dgdavid requested changes

2023-03-22 08:45 UTC, dgdavid commented on service/package/rubygem-d-installer.changes
> +  (gh#yast/d-installer#86).
#86 or #486 ?

2023-03-22 08:50 UTC, imobachgs commented on service/package/rubygem-d-installer.changes
> +  (gh#yast/d-installer#86).
Oh, you are right, the number is wrong.

2023-03-22 11:38 UTC, imobachgs approved these changes

2023-03-22 11:40 UTC, merged